version: '3.9'
services:
  dev:
    build: .
    volumes:
    - .:/code
    read_only: false  # Explicitly allow modifying the image, since we are developing.
    entrypoint: [/usr/bin/tail, -f, /dev/null]
  super-linter:
    image: github/super-linter
    # We should not modify the image, just save the output log.
    read_only: true
    security_opt:
      - "no-new-privileges:true"
    working_dir: /tmp/lint
    volumes:
    - .:/tmp/lint
    environment:
    - RUN_LOCAL=true
  test-latest: &test-latest
    image: ghcr.io/par-tec/super-sast:latest
    read_only: false  # Super-sast downloads updated rules in /tmp/.
    security_opt:
      - "no-new-privileges:true"
    volumes:
    - .:/code
    environment:
    - M2_HOME=/code  # Store maven packages in the shared folder.
    - USER=nobody
    working_dir: /code
  test:
    <<: *test-latest
    build: .
    user: "${UID}"
    environment:
      - M2_HOME=/code
      - HOME=/tmp
      - USER=nobody
      - RUN_OWASP_DEPENDENCY_CHECK=false
      - RUN_SPOTBUGS_CHECK=false
      - RUN_SPOTLESS_CHECK=false
      - RUN_SPOTLESS_APPLY=true
    entrypoint: ["tox"]
